"""empty message

Revision ID: 3f657bd23260
Revises: b0513ffdbc57
Create Date: 2021-05-17 19:36:42.362769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f657bd23260'
down_revision = 'b0513ffdbc57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('owner', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'owner')
    # ### end Alembic commands ###
