"""empty message

Revision ID: 73bf6a70dccd
Revises: fd8911600c00
Create Date: 2021-05-23 12:45:03.066533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bf6a70dccd'
down_revision = 'fd8911600c00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_is_confurmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_is_confurmed')
    # ### end Alembic commands ###
