version: '3'
services:
  web:
    container_name: todo_web
    restart: always
    build: app
    env_file:
      - .env
    ports:
      - '5000:5000'
    volumes:
      - ./app:/usr/src/app
    depends_on:
      -  db

  db:
    container_name: todo_db
    image: postgres:13
    restart: always
    # command: chmod 0700 /var/lib/postgresql/data
    env_file:
      - .env
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080